search-compile:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ ParallelSearch.enc -o shortestpath

search-run:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ --run ParallelSearch.enc

Wordcount-run:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ --run WordCount.enc

Wordcount-compile:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ -o program mapReduceTest.enc
