maptest:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ --run mapReduceTest.enc

main:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ --run main.enc

mapc:
	encorec -I ../bigvar-array/ -I ../map-reduce/ -I ../bigvar-hashtable/ -c mapReduceTest.enc
